site_name: simple-3dviz
site_url: http://simple-3dviz.com/
repo_url: https://github.com/angeloskath/simple-3dviz/
theme: readthedocs
site_dir: output
pages:
- Home: 'index.md'
- User Guide:
  - Loading and Configuring Models: 'data_loading.md'
  - Creating Scenes: 'scene.md'
  - Cameras Manipulation: 'camera.md'
  - Lights Manipulation: 'lights.md'
  - Off-screen Rendering: 'offscreen_rendering.md'
  - Animations: 'animations.md'
- Code walkthrough: 'code-walkthrough.md'
- API Docs: '/api-docs/'
- Examples: 'examples.md'
- Contribution: 'contribution.md'
